# Generated by Django 5.0 on 2023-12-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resolution_id_alter_status_id_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='Statuses',
        ),
    ]
