# Generated by Django 5.0 on 2023-12-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_assignee_alter_task_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='task',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
