# Generated by Django 5.0.1 on 2024-01-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='request_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
