# Generated by Django 5.0.1 on 2024-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_log_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
