# Generated by Django 5.0.1 on 2024-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_github_name_project_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response_payload',
            field=models.TextField(null=True),
        ),
    ]
